# Generated by Django 3.2 on 2022-02-28 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.CharField(blank=True, max_length=50, null=True, verbose_name='ক্রমিক নং')),
                ('name_ban', models.CharField(max_length=50, verbose_name='নাম (বাংলা)')),
                ('name_eng', models.CharField(max_length=50, verbose_name='নাম (English)')),
                ('fathers_name_bangla', models.CharField(max_length=50, verbose_name=' পিতার নাম (বাংলা)')),
                ('fathers_name', models.CharField(max_length=50, verbose_name='পিতার নাম (English)')),
                ('mothers_name_bangla', models.CharField(max_length=50, verbose_name='মাতার নাম (বাংলা)')),
                ('mothers_name', models.CharField(max_length=50, verbose_name='মাতার নাম (English)')),
                ('marital_status', models.CharField(choices=[('Single(অবিবাহিত)', 'Single(অবিবাহিত)'), ('Married(বিবাহিত)', 'Married(বিবাহিত)'), ('Divorced(তালাকপ্রাপ্ত)', 'Divorced(তালাকপ্রাপ্ত)'), ('Widowed(বিধবা)', 'Widowed(বিধবা)')], max_length=50, verbose_name='বৈবাহিক অবস্থা')),
                ('present_address', models.CharField(max_length=100, verbose_name='বর্তমান ঠিকানা')),
                ('village', models.CharField(max_length=50, verbose_name='গ্র্রাম')),
                ('ps', models.CharField(max_length=50, verbose_name='থানা')),
                ('post_office', models.CharField(max_length=50, verbose_name='ডাকঘর')),
                ('date_of_birth', models.DateField(verbose_name='জন্মতারিখ')),
                ('religion', models.CharField(max_length=50, verbose_name='ধর্ম')),
                ('nid_BC', models.CharField(max_length=25, verbose_name='জন্মনিবন্ধন/জাতীয় পরিচয়পত্র নং')),
                ('education', models.CharField(choices=[('MASTERS', 'MASTERS'), ('BACHELOR', 'BACHELOR'), ('H.S.C', 'H.S.C'), ('S.S.C', 'S.S.C'), ('J.S.C', 'J.S.C'), ('P.S.C', 'P.S.C')], max_length=50, verbose_name='শিক্ষাগত যোগ্যতা')),
                ('phone', models.CharField(max_length=11, verbose_name='মোবাইল')),
                ('picture', models.ImageField(upload_to='uploads/', verbose_name='ছবি')),
                ('status', models.CharField(choices=[('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Waiting', 'Waiting'), ('Successfully Done', 'Successfully Done')], max_length=50, verbose_name='সিদ্ধান্ত')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50, verbose_name='শীরনাম')),
                ('description', models.TextField(max_length=500, verbose_name='বর্ণনা')),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='নাম')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50, verbose_name='Project Title')),
                ('description', models.TextField(max_length=500, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Resolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='শীরনাম')),
                ('short_description', models.TextField(max_length=500, verbose_name='বর্ণনা')),
                ('detail', models.TextField(max_length=1000, verbose_name='বিস্তারিত বর্ণনা')),
                ('file_1', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Sub_district',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='নাম')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.district', verbose_name='জেলা')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_year', models.CharField(max_length=50, verbose_name='শীরনাম')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session', to='core.course', verbose_name='কোর্স')),
            ],
        ),
        migrations.CreateModel(
            name='Financial_aid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ammount', models.FloatField()),
                ('Detail', models.TextField(max_length=400, verbose_name='বিস্তারিত')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.applicant')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='Project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project', to='core.project', verbose_name='Project'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.course', verbose_name='কোর্স'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.district', verbose_name='জেলা'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicants', to='core.session', verbose_name='সেশন'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='sub_district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.sub_district', verbose_name='উপজেলা'),
        ),
    ]
