# Generated by Django 3.2 on 2022-01-23 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20220122_1339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='user',
        ),
        migrations.AlterField(
            model_name='applicant',
            name='roll_no',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ক্রমিক নং'),
        ),
    ]
