# Generated by Django 3.2 on 2022-01-23 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20220123_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Rejected', 'Rejected')], max_length=50, verbose_name='সিদ্ধান্ত'),
        ),
        migrations.AlterField(
            model_name='district',
            name='name',
            field=models.CharField(max_length=30, verbose_name='নাম'),
        ),
        migrations.AlterField(
            model_name='financial_aid',
            name='Detail',
            field=models.TextField(max_length=400, verbose_name='বিস্তারিত'),
        ),
        migrations.AlterField(
            model_name='resolution',
            name='detail',
            field=models.TextField(max_length=1000, verbose_name='বিস্তারিত বর্ণনা'),
        ),
        migrations.AlterField(
            model_name='resolution',
            name='short_description',
            field=models.TextField(max_length=500, verbose_name='বর্ণনা'),
        ),
        migrations.AlterField(
            model_name='resolution',
            name='title',
            field=models.CharField(max_length=50, verbose_name='শীরনাম'),
        ),
        migrations.AlterField(
            model_name='session',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session', to='core.course', verbose_name='কোর্স'),
        ),
        migrations.AlterField(
            model_name='sub_district',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.district', verbose_name='জেলা'),
        ),
        migrations.AlterField(
            model_name='sub_district',
            name='name',
            field=models.CharField(max_length=30, verbose_name='নাম'),
        ),
    ]
