# Generated by Django 3.1.4 on 2022-02-20 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20220123_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='education',
            field=models.CharField(choices=[('MASTERS', 'MASTERS'), ('BACHELOR', 'BACHELOR'), ('H.S.C', 'H.S.C'), ('S.S.C', 'S.S.C'), ('J.S.C', 'J.S.C'), ('P.S.C', 'P.S.C')], max_length=50, verbose_name='শিক্ষাগত যোগ্যতা'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='marital_status',
            field=models.CharField(choices=[('Single(অবিবাহিত)', 'Single(অবিবাহিত)'), ('Married(বিবাহিত)', 'Married(বিবাহিত)'), ('Divorced(তালাকপ্রাপ্ত)', 'Divorced(তালাকপ্রাপ্ত)'), ('Widowed(বিধবা)', 'Widowed(বিধবা)')], max_length=50, verbose_name='বৈবাহিক অবস্থা'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='mothers_name',
            field=models.CharField(max_length=50, verbose_name='মাতার নাম (English)'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Waiting', 'Waiting'), ('Successfully Done', 'Successfully Done')], max_length=50, verbose_name='সিদ্ধান্ত'),
        ),
        migrations.AlterField(
            model_name='course',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='district',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='financial_aid',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='resolution',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='session',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sub_district',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
