# Generated by Django 3.1.4 on 2022-02-22 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20220220_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='resolution',
            name='file_1',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
